### ISSUE TITLE
[Question] ToggleButton能不能够使用其他颜色？

### ISSUE THREAD

**Issue by DancingSnow0517** [zhiyiYo/PyQt-Fluent-Widgets#166]
现在想要实现一个功能，想要ToggleButton能够使用别的颜色，请问有什么方法做到吗？

**Comment by zhiyiYo** [comment]
得重新设置 ToggleButton 的样式，主要改 checked 状态下的样式

**Comment by DancingSnow0517** [comment]
请问下，怎么实现比较好？谢谢

**Comment by zhiyiYo** [comment]
test.qss
```css
PushButton,
ToggleButton {
    color: black;
    background: rgba(255, 255, 255, 0.7);
    border: 1px solid rgba(0, 0, 0, 0.073);
    border-bottom: 1px solid rgba(0, 0, 0, 0.183);
    border-radius: 5px;
    font: 14px 'Segoe UI', 'Microsoft YaHei';
    padding: 5px 12px 6px 12px;
    outline: none;
}

ToggleButton[hasIcon=false] {
    padding: 5px 12px 6px 12px;
}

ToggleButton[hasIcon=true] {
    padding: 5px 12px 6px 36px;
}


ToggleButton:hover {
    background: rgba(249, 249, 249, 0.5);
}

ToggleButton:pressed {
    color: rgba(0, 0, 0, 0.63);
    background: rgba(249, 249, 249, 0.3);
    border-bottom: 1px solid rgba(0, 0, 0, 0.073);
}

ToggleButton:disabled {
    color: rgba(0, 0, 0, 0.36);
    background: rgba(249, 249, 249, 0.3);
    border: 1px solid rgba(0, 0, 0, 0.06);
    border-bottom: 1px solid rgba(0, 0, 0, 0.06);
}


ToggleButton:checked {
    color: white;
    background-color: #2b96e5;
    border: 1px solid #2d9ef0;
    border-bottom: 1px solid #2071ac;
}

ToggleButton:checked:hover {
    background-color: #2d9ef0;
    border: 1px solid #5eb2f0;
    border-bottom: 1px solid #2071ac;
}

ToggleButton:checked:pressed {
    color: rgba(255, 255, 255, 0.63);
    background-color: #72bbf0;
    border: 1px solid #72bbf0;
}

ToggleButton:checked:disabled {
    color: rgba(255, 255, 255, 0.9);
    background-color: rgb(205, 205, 205);
    border: 1px solid rgb(205, 205, 205);
}
```

test.py
```python
# coding:utf-8
import sys
from qfluentwidgets import ToggleButton
from qfluentwidgets.common.style_sheet import styleSheetManager

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget


class Demo(QWidget):

    def __init__(self):
        super().__init__()
        self.button = ToggleButton('切换按钮', self)
        self.resize(500, 500)
        self.button.move(200, 200)

        # 不让 qfluentwidgets 管理这个按钮的样式
        styleSheetManager.deregister(self.button)

        # 设置为自定义样式，这里只写了浅色模式下的样式，关于如何在亮暗模式下切换自定义样式可以看下文档
        # https://pyqt-fluent-widgets.readthedocs.io/zh_CN/latest/theme.html
        with open('test.qss', encoding='utf-8') as f:
            self.button.setStyleSheet(f.read())



if __name__ == '__main__':
    # enable dpi scale
    QApplication.setHighDpiScaleFactorRoundingPolicy(
        Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)

    app = QApplication(sys.argv)
    w = Demo()
    w.show()
    app.exec_()
```
