### ISSUE TITLE
list/table widget无法设置单元格颜色

### ISSUE THREAD

**Issue by abcdesteve** [zhiyiYo/PyQt-Fluent-Widgets#233]
list/table widget无法设置单元格颜色
```python
QTableWidgetItem.setBackground(QColor('green'))
```
其中`QTableWidget`已提升为`TableWidget`
执行后仍然没有颜色

**Comment by zhiyiYo** [comment]
样式表设置了 Item 样式，所以无法再设置背景色了

**Comment by AmirMahdaviAM** [comment]
how can i change it from stylesheet (for ListWidget)?
i edited background color in qss file and apply it but background still unchanged
(i know applied because of padding changed)

```css
#taskList {
    background: rgba(255, 255, 255, 0.100);
    outline: none;
    border: none;
    padding-left: 15px;
    padding-right: 15px;
    padding-top: 15px;
    padding-bottom: 15px;
}

#taskList::item {
    background: rgba(255, 255, 255, 0.100);
    padding-left: 15px;
    padding-right: 15px;
    padding-top: 15px;
    padding-bottom: 15px;
}
```

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/32765143/60744d00-7ce7-4c15-b530-8df5d07d1317)
