### ISSUE TITLE
[Bug]: Change background of ListWidget item

### ISSUE THREAD

**Issue by AmirMahdaviAM** [zhiyiYo/PyQt-Fluent-Widgets#869]
### What happened?

how can i change item list background?

use setBackground but it will break all other visuals
```python
item = QListWidgetItem(itemText)
setFont(item)
item.setBackground(QColor(255, 255, 255, 10))
self.taskList.addItem(item)
```

and then edited background color in qss file and apply it but background still unchanged
(i know applied because of padding changed)

```css
#taskList::item {
    background: rgba(255, 255, 255, 0.100);
    padding-left: 15px;
    padding-right: 15px;
    padding-top: 15px;
    padding-bottom: 15px;
}
```

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/32765143/60744d00-7ce7-4c15-b530-8df5d07d1317)

### Operation System

Windows11 22h2

### Python Version

3.10.6

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

1.5.6

### How to Reproduce?

ListWidget::item {
    background: rgba(255, 255, 255, 0.100);
}

item.setBackground(QColor(255, 255, 255, 10))

### Minimum code

```python3
self.taskList = ListWidget(self)
self.taskList.setObjectName("taskList")

item = QListWidgetItem(itemText)
setFont(item)
item.setBackground(QColor(255, 255, 255, 10))
self.taskList.addItem(item)
```
